theme: jekyll-theme-slate
title: This is a personal homepage belonging to Jesus Giovanni, an MJSP student of Hokkaido University.
description: Some snippets of information, and maybe links, are going to go here.
plugins:
  - jemoji
url: "https://giojpg.github.io/"
markdown: kramdown
